### ISSUE TITLE
Make the description of each column configurable. 

### ISSUE THREAD

**Issue by k-kawa** [k-kawa/bqv#10]

**Comment by irotoris** [comment]
SQLのコメントから特定文字列パースするのと、別ファイルでdescription持たすのとどっちがいいですかね？
後者だと仕様と実装は簡潔になりそうですが、SQLファイルのみで管理できなくなってSimpleさが無くなりそうな気がしています。

**Comment by k-kawa** [comment]
> @irotoris さんが思う最高の実装を強く主張して、それを実装してマージしてください！マージする権限はありますよね。
> 既存の機能を壊さない範囲なら、よしなにやっちゃいましょう！まだv0なんで。

というのが基本スタンスですが、個人的には後者のほうがいいかなと思います。
他にも、将来 SQL で表現できないけど宣言的に書いて管理したい項目が出てくるだろうと思うからです。たとえば、View のアクセス権とか、ラベルとかです。
そういう変更が将来起こることを見越して、 `query.sql` と同じディレクトリに `meta.yaml` とかを置いておくと良しなに読んで解釈してくれる、なければ単に view を作るだけ、みたいな仕様がよいと思います。

**Comment by irotoris** [comment]
`meta.json`書いたらよしなにカラムの説明を追加してくれるようにしました。 #33 
Done!!
